language: node_js
node_js: - stable
cache: npm

#before_install:
install:
  - npm ci

#before_script:
script:
  - npm test
  - npm run build
#after_success:
#after_failure:
#after_script:
#before_deploy:
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
<<<<<<< HEAD
<<<<<<< HEAD
    branch: temp
=======
    branch: master
>>>>>>> dbb2cd2610a464b9b2e94234e7bd37f9dd580376
=======

    branch: master

>>>>>>> deef9b9e008ca9238045eae819d4ae740cee16a1
#after_deploy:
#
